######################################################################
# Automatically generated by qmake (2.01a) lun nov 9 18:13:05 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += render.h window.h
SOURCES += main.cpp render.cpp window.cpp
RESOURCES += qml.qrc

FORMS += \
    form.ui
