######################################################################
# Automatically generated by qmake (2.01a) lun nov 9 12:53:36 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
